🩹 Exclude optimization_history.csv and parameter_history.csv from map_result_parameters
The type ignore is needed because of the difference between numpys 'floating[_32Bit]' and python float.
pyglotaran-examples/test_result_consistency.py:255: error: Incompatible types in assignment (expression has type "float", variable has type "floating[_32Bit]")  [assignment]